// Study recommendation templates.
// Each study combines foundation relevance, genre concepts, prerequisites,
// a transparent focus sequence, and an application prompt that does not
// supply the musical answer.

export const STUDY_CATEGORIES = {
  foundation: {
    id: 'foundation',
    label: 'Foundation Study',
    blurb: 'Repairs missing general knowledge every musician needs.',
  },
  'genre-vocabulary': {
    id: 'genre-vocabulary',
    label: 'Genre Vocabulary Study',
    blurb: 'Introduces a concept frequently useful in your saved genres.',
  },
  weakness: {
    id: 'weakness',
    label: 'Weakness Study',
    blurb: 'Targets repeated errors or slow recognition.',
  },
  transfer: {
    id: 'transfer',
    label: 'Transfer Study',
    blurb: 'Moves known material to a new fretboard region or context.',
  },
  retention: {
    id: 'retention',
    label: 'Retention Review',
    blurb: 'Revisits knowledge before it decays.',
  },
  contrast: {
    id: 'contrast',
    label: 'Contrast Study',
    blurb: 'Compares related structures to prevent confusion.',
  },
  application: {
    id: 'application',
    label: 'Application Study',
    blurb: 'Uses learned theory in a short musical context.',
  },
};

/**
 * @typedef {object} StudyDef
 * @property {string} id
 * @property {string} title
 * @property {keyof typeof STUDY_CATEGORIES} category
 * @property {string[]} concepts
 * @property {string[]} [prerequisites]
 * @property {number} foundationWeight  // 0..1 — how foundational
 * @property {string} [scale]           // musical context scale name
 * @property {string} toolId            // primary tool to open
 * @property {string[]} [altTools]
 * @property {string[]} focus           // numbered focus steps
 * @property {string} [application]     // genre-framed prompt (no answers)
 * @property {string} summary           // short description
 * @property {string[]} [applications]  // application preference tags
 * @property {string[]} [skillIds]      // stats.js skill ids that signal weakness
 */

/** @type {StudyDef[]} */
export const STUDY_CATALOG = [
  // ——— Foundation ———
  {
    id: 'major-scale-construction',
    title: 'Major-Scale Construction',
    category: 'foundation',
    concepts: ['major_scale', 'interval_locations'],
    prerequisites: [],
    foundationWeight: 1,
    scale: 'Major (Ionian)',
    toolId: 'scales',
    altTools: ['scaleref', 'fretboard'],
    skillIds: ['scale', 'fretboard'],
    applications: ['fretboard', 'harmony'],
    summary: 'Build the major scale from intervals so every modal comparison has a reference point.',
    focus: [
      'Recall the major-scale interval formula from an arbitrary tonic.',
      'Spell the seven degrees without looking at a diagram.',
      'Map the scale on one string, then in a five-fret box.',
      'Name each degree as an interval from the tonic.',
    ],
    application: 'Choose any tonic and write a four-note ascending phrase that clearly outlines 1–2–3–5. Pick the frets yourself.',
  },
  {
    id: 'interval-locations',
    title: 'Interval Location Drill',
    category: 'foundation',
    concepts: ['interval_locations', 'fretboard_transfer'],
    prerequisites: [],
    foundationWeight: 1,
    toolId: 'intervalorbit',
    altTools: ['intervals', 'fretboard'],
    skillIds: ['intervalorbit', 'interval', 'fretboard'],
    applications: ['fretboard', 'ear'],
    summary: 'Locate intervals around an anchor root so chord construction stays interval-first.',
    focus: [
      'Pick an anchor root on any string.',
      'Locate b3, 3, 5, and b7 relative to that root.',
      'Repeat the same intervals starting from a different string.',
      'Name each shape by interval fingerprint, not note name.',
    ],
    application: 'Build a three-note shape using only 1, b3, and 5 from a root you choose. Do not rely on a memorized chord name.',
  },
  {
    id: 'major-minor-triads',
    title: 'Major and Minor Triad Construction',
    category: 'foundation',
    concepts: ['major_minor_triads', 'interval_locations'],
    prerequisites: ['major_scale'],
    foundationWeight: 0.95,
    scale: 'Major (Ionian)',
    toolId: 'triads',
    altTools: ['chordlab', 'chords'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'fretboard'],
    summary: 'Construct major and minor triads from interval fingerprints before specializing in darker harmony.',
    focus: [
      'Build a major triad as 1–3–5 from any root.',
      'Build a minor triad as 1–♭3–5 from the same root.',
      'Identify each quality without naming the root pitch.',
      'Place both qualities on at least two string sets.',
    ],
    application: 'Connect one major and one minor triad using the closest available voicing. Move no voice farther than necessary.',
  },
  {
    id: 'triad-inversions',
    title: 'Triad Inversion Fluency',
    category: 'foundation',
    concepts: ['triad_inversions', 'major_minor_triads', 'voice_leading'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.9,
    toolId: 'triads',
    altTools: ['chords', 'chordlab'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'songwriting'],
    summary: 'Invert triads so voice leading and fretboard connection stay smooth.',
    focus: [
      'Spell root position, first inversion, and second inversion for one triad.',
      'Find each inversion on a single string set.',
      'Identify inversions root-blind by interval shape.',
      'Connect two inversions with minimal hand travel.',
    ],
    application: 'Connect two diatonic chords using the closest available inversion. Do not move any voice farther than necessary.',
  },
  {
    id: 'diatonic-harmony',
    title: 'Diatonic Triad Harmony',
    category: 'foundation',
    concepts: ['diatonic_harmony', 'major_minor_triads', 'major_scale'],
    prerequisites: ['major_scale', 'major_minor_triads'],
    foundationWeight: 0.9,
    scale: 'Major (Ionian)',
    toolId: 'chords',
    altTools: ['scaleref', 'circle'],
    skillIds: ['scale', 'chordlab'],
    applications: ['harmony', 'songwriting'],
    summary: 'Derive the seven diatonic triads so modal and minor harmony have a comparison point.',
    focus: [
      'Spell the major scale from an arbitrary tonic.',
      'Stack thirds on every degree to form triads.',
      'Label each triad quality without shortcuts.',
      'Name the function of I, IV, and V in plain language.',
    ],
    application: 'Arrange three diatonic triads into a short progression and explain why each belongs to the key.',
  },

  // ——— Genre vocabulary / metal family ———
  {
    id: 'harmonic-minor-map',
    title: 'Harmonic Minor Mapping',
    category: 'genre-vocabulary',
    concepts: ['harmonic_minor', 'natural_minor', 'interval_locations'],
    prerequisites: ['major_scale', 'natural_minor'],
    foundationWeight: 0.55,
    scale: 'Harmonic Minor',
    toolId: 'scaleref',
    altTools: ['scales', 'fretboard'],
    skillIds: ['scale', 'fretboard'],
    applications: ['fretboard', 'harmony', 'improvisation'],
    summary: 'Map harmonic minor and hear the raised seventh as tension against natural minor.',
    focus: [
      'Recall the harmonic-minor interval formula.',
      'Map it from an arbitrary tonic on one string.',
      'Transfer the scale into a five-fret region.',
      'Compare degree 7 with natural minor’s ♭7.',
    ],
    application: 'Create a four-degree phrase that emphasizes 1, ♭6, and 7. Choose the frets and rhythm yourself.',
  },
  {
    id: 'harmonic-minor-triads',
    title: 'Harmonic Minor Triad Discovery',
    category: 'genre-vocabulary',
    concepts: ['harmonic_minor', 'major_minor_triads', 'diminished_triads', 'augmented_triads', 'root_blind_quality'],
    prerequisites: ['major_minor_triads', 'harmonic_minor'],
    foundationWeight: 0.5,
    scale: 'Harmonic Minor',
    toolId: 'triads',
    altTools: ['scaleref', 'chordlab'],
    skillIds: ['chordlab', 'scale'],
    applications: ['harmony', 'fretboard'],
    summary: 'Construct all seven triads in harmonic minor and identify them by interval fingerprint.',
    focus: [
      'Map harmonic minor from an arbitrary tonic.',
      'Construct triads from all seven degrees.',
      'Identify each triad using interval fingerprints.',
      'Practice the diminished-seventh three-fret cycle.',
      'Apply the results in a short rhythmic or melodic exercise.',
    ],
    application: 'Select one minor, one major, and one diminished triad from the scale. Arrange them into a three-chord sequence and explain why each belongs to the scale.',
  },
  {
    id: 'harmonic-minor-harmony-symmetry',
    title: 'Harmonic Minor Harmony and Symmetry',
    category: 'genre-vocabulary',
    concepts: ['harmonic_minor', 'dim7', 'symmetry_rules', 'diminished_triads', 'augmented_triads', 'seventh_chords'],
    prerequisites: ['harmonic_minor', 'major_minor_triads'],
    foundationWeight: 0.45,
    scale: 'Harmonic Minor',
    toolId: 'scaleref',
    altTools: ['triads', 'chords', 'intervalorbit'],
    skillIds: ['scale', 'chordlab', 'intervalorbit'],
    applications: ['harmony', 'fretboard', 'improvisation'],
    summary: 'Use harmonic minor as a lab for mixed triad qualities and diminished-seventh symmetry.',
    focus: [
      'Recall the harmonic-minor interval formula.',
      'Map it from an arbitrary tonic on one string.',
      'Transfer the scale into a five-fret region.',
      'Construct all seven triads using alternating degrees.',
      'Identify the triads without using note names.',
      'Extend the diminished triad into a fully diminished seventh.',
      'Move the diminished-seventh form through the three-fret symmetry cycle.',
      'Create a short progression using one minor, one major, and one diminished structure.',
    ],
    application: 'Suggest a rhythmic or melodic context from your genre, but select the notes, chord order, and fretboard positions yourself.',
  },
  {
    id: 'phrygian-mapping',
    title: 'Phrygian Interval Mapping',
    category: 'genre-vocabulary',
    concepts: ['phrygian', 'flat2', 'natural_minor', 'interval_locations'],
    prerequisites: ['natural_minor', 'interval_locations'],
    foundationWeight: 0.4,
    scale: 'Phrygian',
    toolId: 'scaleref',
    altTools: ['scales', 'intervalorbit'],
    skillIds: ['scale', 'intervalorbit'],
    applications: ['fretboard', 'improvisation', 'technique'],
    summary: 'Map Phrygian with emphasis on the ♭2 color used in darker tonal movement.',
    focus: [
      'Spell Phrygian from an arbitrary tonic.',
      'Locate ♭2 relative to the tonic on every adjacent string.',
      'Compare Phrygian with natural minor at the same tonic.',
      'Map a low-register box useful for riff construction.',
    ],
    application: 'Create a four-degree phrase that emphasizes 1, ♭2, and ♭3. Use a repeated rhythm associated with your selected genre, but choose the fretboard positions yourself.',
  },
  {
    id: 'phrygian-dominant-mapping',
    title: 'Phrygian Dominant Interval Mapping',
    category: 'genre-vocabulary',
    concepts: ['phrygian_dominant', 'flat2', 'harmonic_minor', 'interval_locations'],
    prerequisites: ['phrygian', 'major_minor_triads'],
    foundationWeight: 0.35,
    scale: 'Phrygian Dominant',
    toolId: 'scaleref',
    altTools: ['scales', 'intervalorbit'],
    skillIds: ['scale', 'intervalorbit'],
    applications: ['fretboard', 'improvisation', 'technique'],
    summary: 'Map Phrygian dominant and isolate the 1–♭2–3 fingerprint.',
    focus: [
      'Recall how Phrygian dominant relates to harmonic minor.',
      'Map 1, ♭2, and 3 from an arbitrary tonic.',
      'Compare the major third against Phrygian’s ♭3.',
      'Transfer the shape into a disconnected fretboard region.',
    ],
    application: 'Create a four-degree phrase that emphasizes 1, ♭2, and 3. Use a repeated rhythm associated with your selected genre, but choose the fretboard positions yourself.',
  },
  {
    id: 'dorian-minor-sixth',
    title: 'Dorian Natural-Sixth Color',
    category: 'genre-vocabulary',
    concepts: ['dorian', 'natural_minor', 'modal_comparison'],
    prerequisites: ['natural_minor'],
    foundationWeight: 0.45,
    scale: 'Dorian',
    toolId: 'scaleref',
    altTools: ['scales'],
    skillIds: ['scale'],
    applications: ['improvisation', 'harmony', 'fretboard'],
    summary: 'Hear Dorian as minor harmony with a natural sixth rather than a separate “genre scale.”',
    focus: [
      'Spell Dorian and natural minor from the same tonic.',
      'Isolate the natural 6 versus ♭6 contrast.',
      'Map both scales in one fretboard region.',
      'Target chord tones over a static minor tonic.',
    ],
    application: 'Write a short phrase that lands on the natural sixth, then resolve to 1 or ♭3. Choose positions yourself.',
  },
  {
    id: 'diminished-harmony-lab',
    title: 'Diminished Harmony Lab',
    category: 'weakness',
    concepts: ['diminished_triads', 'dim7', 'symmetry_rules', 'tritone'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.4,
    toolId: 'chords',
    altTools: ['triads', 'intervalorbit'],
    skillIds: ['chordlab', 'intervalorbit'],
    applications: ['harmony', 'fretboard'],
    summary: 'Recognize diminished triads and fully diminished sevenths by interval fingerprint and symmetry.',
    focus: [
      'Construct a diminished triad as 1–♭3–♭5.',
      'Extend it to a fully diminished seventh.',
      'Move the dim7 form through the three-fret cycle.',
      'Explain the cycle as interval symmetry, not a fingering trick.',
    ],
    application: 'Place one diminished structure under a pedal tone you choose. Do not ask the app to pick the frets.',
  },
  {
    id: 'augmented-symmetry',
    title: 'Augmented Triad Symmetry',
    category: 'genre-vocabulary',
    concepts: ['augmented_triads', 'symmetry_rules', 'harmonic_minor'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.35,
    toolId: 'triads',
    altTools: ['chords', 'intervalorbit'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'fretboard'],
    summary: 'Connect the four-fret augmented cycle to equal octave division.',
    focus: [
      'Build an augmented triad as 1–3–♯5.',
      'Move the shape by four frets and confirm enharmonic equivalence.',
      'Find an augmented triad inside harmonic minor.',
      'Identify the quality root-blind.',
    ],
    application: 'Use one augmented triad as a passing color between two minor-key chords you select.',
  },

  // ——— Contrast ———
  {
    id: 'phrygian-vs-phrygian-dominant',
    title: 'Phrygian vs Phrygian Dominant',
    category: 'contrast',
    concepts: ['phrygian', 'phrygian_dominant', 'flat2', 'modal_comparison'],
    prerequisites: ['phrygian'],
    foundationWeight: 0.35,
    scale: 'Phrygian',
    toolId: 'scaleref',
    altTools: ['scales'],
    skillIds: ['scale'],
    applications: ['fretboard', 'improvisation', 'ear'],
    summary: 'Compare the ♭3 / 3 difference so the two dark flavors stay distinct.',
    focus: [
      'Map Phrygian and Phrygian dominant from the same tonic.',
      'Isolate ♭3 versus 3 while keeping ♭2 fixed.',
      'Sing or hum the contrasting third.',
      'Write one phrase for each quality without mixing them accidentally.',
    ],
    application: 'Play two short phrases — one Phrygian, one Phrygian dominant — and state which degree changed.',
  },
  {
    id: 'natural-vs-harmonic-minor',
    title: 'Natural Minor vs Harmonic Minor',
    category: 'contrast',
    concepts: ['natural_minor', 'harmonic_minor', 'modal_comparison'],
    prerequisites: ['natural_minor'],
    foundationWeight: 0.5,
    scale: 'Natural Minor (Aeolian)',
    toolId: 'scaleref',
    altTools: ['scales'],
    skillIds: ['scale'],
    applications: ['harmony', 'improvisation', 'ear'],
    summary: 'Keep Aeolian and harmonic minor distinct by focusing on degree 7.',
    focus: [
      'Spell both scales from one tonic.',
      'Compare ♭7 and 7 in the same fretboard box.',
      'Derive the V chord implied by the raised seventh.',
      'Identify which scale a short phrase implies.',
    ],
    application: 'Write one riff that uses ♭7 and one that uses 7. Keep the tonic and rhythm identical.',
  },
  {
    id: 'dim-triad-vs-dim7',
    title: 'Diminished Triad vs Fully Diminished Seventh',
    category: 'contrast',
    concepts: ['diminished_triads', 'dim7', 'seventh_chords'],
    prerequisites: ['diminished_triads'],
    foundationWeight: 0.4,
    toolId: 'chords',
    altTools: ['triads'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'ear'],
    summary: 'Separate three-note diminished color from the four-note symmetrical seventh.',
    focus: [
      'Build both structures from the same root.',
      'Name the added interval that creates dim7.',
      'Compare their symmetry behavior on the fretboard.',
      'Identify each quality root-blind.',
    ],
  },
  {
    id: 'maj7-vs-dom7',
    title: 'Major Seventh vs Dominant Seventh',
    category: 'contrast',
    concepts: ['maj7', 'dominant7', 'seventh_chords', 'flat7'],
    prerequisites: ['major_minor_triads', 'seventh_chords'],
    foundationWeight: 0.55,
    toolId: 'chords',
    altTools: ['chordlab'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'ear', 'songwriting'],
    summary: 'Contrast maj7 and dominant 7 by the quality of the seventh.',
    focus: [
      'Build both chords as triad + seventh.',
      'Locate 7 versus ♭7 from the same root.',
      'Voice each as guide tones (3 and 7).',
      'Identify the quality without the root sounding.',
    ],
  },

  // ——— Transfer / retention / application ———
  {
    id: 'harmonic-minor-transfer',
    title: 'Harmonic Minor Upper-String Transfer',
    category: 'transfer',
    concepts: ['harmonic_minor', 'fretboard_transfer'],
    prerequisites: ['harmonic_minor'],
    foundationWeight: 0.35,
    scale: 'Harmonic Minor',
    toolId: 'fretboard',
    altTools: ['scaleref', 'intervalorbit'],
    skillIds: ['fretboard', 'scale'],
    applications: ['fretboard', 'technique'],
    summary: 'Rebuild harmonic minor on the upper three strings without your familiar position.',
    focus: [
      'Choose a tonic far from your usual starting fret.',
      'Map harmonic minor on the upper three strings only.',
      'Locate degree 7 without referencing the lower strings.',
      'Play a short sequence that crosses into a new five-fret region.',
    ],
    application: 'Improvise four bars using only the transferred region. No open-position safety nets.',
  },
  {
    id: 'modal-comparison-lab',
    title: 'Dorian / Aeolian / Phrygian Comparison',
    category: 'contrast',
    concepts: ['modal_comparison', 'dorian', 'natural_minor', 'phrygian'],
    prerequisites: ['natural_minor'],
    foundationWeight: 0.45,
    scale: 'Natural Minor (Aeolian)',
    toolId: 'scaleref',
    altTools: ['scales'],
    skillIds: ['scale'],
    applications: ['improvisation', 'fretboard', 'ear'],
    summary: 'Compare three minor modes from one tonic to train modal hearing and fretboard transfer.',
    focus: [
      'Compare Dorian, Aeolian, and Phrygian from the same tonic.',
      'Isolate the characteristic degrees (6, ♭6/♭2).',
      'Map each mode in the same five-fret region.',
      'Improvise one phrase per mode without mixing signatures.',
    ],
    application: 'Record or play three short phrases — one per mode — and state the characteristic degree you emphasized.',
  },
  {
    id: 'seventh-chord-lab',
    title: 'Seventh-Chord Recognition Lab',
    category: 'weakness',
    concepts: ['seventh_chords', 'root_blind_quality', 'guide_tones'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.55,
    toolId: 'chordlab',
    altTools: ['chords'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'ear', 'improvisation'],
    summary: 'Derive seventh chords and identify quality with guide tones before relying on root names.',
    focus: [
      'Construct maj7, m7, and dominant 7 from interval formulas.',
      'Isolate 3 and 7 as guide tones.',
      'Identify each quality root-blind.',
      'Place one voicing of each on two string sets.',
    ],
    application: 'Target only guide tones over a two-chord vamp you invent. Do not outline full arpeggios.',
  },
  {
    id: 'pentatonic-major-minor',
    title: 'Major vs Minor Pentatonic',
    category: 'genre-vocabulary',
    concepts: ['major_pentatonic', 'minor_pentatonic', 'melodic_lead'],
    prerequisites: ['major_scale'],
    foundationWeight: 0.5,
    scale: 'Minor Pentatonic',
    toolId: 'scaleref',
    altTools: ['scales', 'fretboard'],
    skillIds: ['scale', 'fretboard'],
    applications: ['improvisation', 'fretboard', 'technique'],
    summary: 'Compare major and minor pentatonic from related tonics for rock and blues vocabulary.',
    focus: [
      'Map minor pentatonic from a tonic.',
      'Map major pentatonic from the relative major.',
      'Notice shared tones and differing centers.',
      'Target chord tones from each collection.',
    ],
    application: 'Play a phrase that starts minor-pentatonic and resolves to a major-pentatonic tone over a major chord you choose.',
  },
  {
    id: 'blues-tension-lab',
    title: 'Blues Tension Vocabulary',
    category: 'genre-vocabulary',
    concepts: ['blues_vocabulary', 'flat3', 'dominant7', 'minor_pentatonic', 'major_pentatonic'],
    prerequisites: ['minor_pentatonic', 'major_minor_triads'],
    foundationWeight: 0.35,
    scale: 'Blues',
    toolId: 'scaleref',
    altTools: ['scales', 'chords'],
    skillIds: ['scale'],
    applications: ['improvisation', 'ear', 'harmony'],
    summary: 'Explain why blues vocabulary may combine intervals that do not belong to one strict diatonic scale.',
    focus: [
      'Compare minor and major pentatonic over a dominant chord.',
      'Locate b3 against a sounding major third.',
      'Add b5 as a passing tone between 4 and 5.',
      'Target chord tones on strong beats.',
    ],
    application: 'Write a two-bar phrase that includes b3 against a major triad or dominant chord. Choose the frets yourself.',
  },
  {
    id: 'jazz-guide-tones',
    title: 'Guide-Tone Voice Leading',
    category: 'genre-vocabulary',
    concepts: ['guide_tones', 'voice_leading', 'seventh_chords'],
    prerequisites: ['seventh_chords'],
    foundationWeight: 0.4,
    toolId: 'chords',
    altTools: ['chordlab'],
    skillIds: ['chordlab'],
    applications: ['harmony', 'improvisation', 'songwriting'],
    summary: 'Move 3rds and 7ths between seventh chords before adding extensions.',
    focus: [
      'Extract 3 and 7 from two adjacent seventh chords.',
      'Voice-lead those tones with minimal motion.',
      'Identify quality from guide tones alone.',
      'Only then add a root or extension.',
    ],
    application: 'Connect two seventh chords using only guide tones. Do not fill in full grips until the line is clear.',
  },
  {
    id: 'pop-progression-functions',
    title: 'Common Progression Functions',
    category: 'genre-vocabulary',
    concepts: ['diatonic_harmony', 'relative_major_minor', 'voice_leading'],
    prerequisites: ['diatonic_harmony'],
    foundationWeight: 0.55,
    scale: 'Major (Ionian)',
    toolId: 'circle',
    altTools: ['chords', 'scaleref'],
    skillIds: ['scale'],
    applications: ['songwriting', 'harmony'],
    summary: 'Practice common diatonic functions and relative major/minor relationships.',
    focus: [
      'Spell I, IV, V, and vi in a major key.',
      'Find the relative minor and its diatonic triads.',
      'Connect chords with smooth inversions.',
      'Explain each chord’s function in plain language.',
    ],
    application: 'Write a four-chord progression and label each chord’s function. Choose voicings yourself.',
  },
  {
    id: 'pedal-tone-interval-map',
    title: 'Pedal-Tone Interval Mapping',
    category: 'application',
    concepts: ['pedal_tones', 'interval_locations', 'dissonant_dyads', 'rhythmic_riff'],
    prerequisites: ['interval_locations'],
    foundationWeight: 0.35,
    toolId: 'intervalorbit',
    altTools: ['fretboard'],
    skillIds: ['intervalorbit', 'fretboard'],
    applications: ['technique', 'fretboard', 'improvisation'],
    summary: 'Map dissonant and consonant intervals above a static low pedal.',
    focus: [
      'Choose a low pedal pitch and keep it ringing or implied.',
      'Map b2, tritone, and 5 above that pedal.',
      'Repeat the interval sequence with a steady rhythm.',
      'Transfer the same relationships one octave higher.',
    ],
    application: 'Build a riff that repeats one interval sequence over a pedal you choose. The app will not pick the notes.',
  },
  {
    id: 'chord-tone-melodic-targeting',
    title: 'Chord-Tone Melodic Targeting',
    category: 'application',
    concepts: ['chord_tone_targeting', 'melodic_lead', 'major_minor_triads'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.4,
    toolId: 'scaleref',
    altTools: ['triads', 'fretboard'],
    skillIds: ['scale', 'fretboard'],
    applications: ['improvisation', 'technique', 'songwriting'],
    summary: 'Build melodic phrases that land on triad tones rather than scale runs alone.',
    focus: [
      'Choose a short minor-key progression (you invent it).',
      'Locate chord thirds on adjacent string sets.',
      'Build phrases that target those thirds on strong beats.',
      'Fill between targets with scale tones of your choice.',
    ],
    application: 'Compose an eight-note melody that hits a chord third on beats one and three. Pick every fret yourself.',
  },
  {
    id: 'root-blind-diminished',
    title: 'Root-Blind Diminished Recognition',
    category: 'weakness',
    concepts: ['root_blind_quality', 'diminished_triads', 'dim7'],
    prerequisites: ['major_minor_triads'],
    foundationWeight: 0.4,
    toolId: 'chordlab',
    altTools: ['triads', 'chords'],
    skillIds: ['chordlab'],
    applications: ['ear', 'harmony'],
    summary: 'Identify diminished structures without depending on a named root.',
    focus: [
      'Build diminished triads from interval fingerprints only.',
      'Hide the root and still name the quality.',
      'Extend to dim7 and re-identify.',
      'Compare against minor and augmented distractors.',
    ],
  },
  {
    id: 'fretboard-wide-intervals',
    title: 'Fretboard-Wide Interval Mapping',
    category: 'transfer',
    concepts: ['fretboard_transfer', 'interval_locations', 'wide_intervals'],
    prerequisites: ['interval_locations'],
    foundationWeight: 0.5,
    toolId: 'intervalorbit',
    altTools: ['fretboard'],
    skillIds: ['intervalorbit', 'fretboard'],
    applications: ['fretboard', 'technique'],
    summary: 'Rebuild known intervals in disconnected fretboard regions.',
    focus: [
      'Pick one interval class (e.g. tritone or ♭2).',
      'Locate it from three different roots.',
      'Force at least one answer onto the upper register.',
      'Force at least one answer into a low-register riff zone.',
    ],
    application: 'Use the same interval in a low riff and a high lead fragment. You choose both positions.',
  },
  {
    id: 'natural-minor-foundation',
    title: 'Natural Minor Construction',
    category: 'foundation',
    concepts: ['natural_minor', 'relative_major_minor', 'major_scale'],
    prerequisites: ['major_scale'],
    foundationWeight: 0.85,
    scale: 'Natural Minor (Aeolian)',
    toolId: 'scales',
    altTools: ['scaleref'],
    skillIds: ['scale'],
    applications: ['harmony', 'fretboard'],
    summary: 'Build natural minor and relate it to its parent major scale.',
    focus: [
      'Spell natural minor from an arbitrary tonic.',
      'Find the relative major.',
      'Map both collections in one region.',
      'Derive the diatonic minor triads.',
    ],
    application: 'Write a three-chord minor progression and name the relative major key.',
  },
];

export function getStudyById(id) {
  return STUDY_CATALOG.find(s => s.id === id) || null;
}

export function studiesForConcept(conceptId) {
  return STUDY_CATALOG.filter(s => s.concepts.includes(conceptId));
}
